### ISSUE TITLE
Reading Capitals and Reading Pnl is very brittle

### ISSUE THREAD

**Issue by changetocoding** [Xietyz/Misc#5]
The code for reading Capitals and Reading Pnl could go horribly wrong if a small change is made to the file. Can you identify a change that would break your code and how would you make your code more robust.

**Comment by Xietyz** [comment]
Missing a date, a date in the wrong place or a date that cant be passed would break the code.
Could fix this by going through the whole row to find a date instead of looking at only index 0. Try-catch blocks would help make it chug along as well.

I was thinking maybe missing a column in one of the rows could break it as well but I'm not too sure?

Anything else? @jacobtimms
